server:
  port: 8090

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false

experian:
  oauth2:
    url: https://uat-us-api.experian.com/oauth2/v1/token
    client-id: 5AUALtffLUEz3NxVVr9gS0WBImq9uskw
    client-secret: qTaPTAEYFuGjhfJO
    username: wsAPIGee
    password: Roger2024
  services:
    url: https://uat-api.experian.cl/cl/cr/cedu0102/v1/cedulas/estado/obtener
    irut_consolidado_morosidad: https://uat-api.experian.cl/cl/cr/irut0202/v1/morosidades/obtener
    iurl_deuda: https://uat-api.experian.cl/cl/cr/irut1603/v1/deudas/obtener
    destino: http://localhost:8080/api/v1/informes

logging:
  level:
    org.springframework.security: OFF
